### PR TITLE
Minor revision

### PR DESCRIPTION
**Pull request by csadorf**

### CODE REVIEW

**Review by yakutovicha — COMMENTED** [review]
thanks @csadorf.

I was wondering whether the `helm upgrade ...` (in the `deploy-jh.sh` file) operation requires helm to be installed on the Kubernetes cluster? As far as I know, this isn't always the case.

Another thing that we might want to add to the README is how to upgrade to another helm chart. In the current state of things, one needs to run `kubectl delete -f full.yaml` to delete the previous configuration. This wouldn't be possible after applying your changes. Do you know how one should deal with that?

**Comment by csadorf** [comment]
> I was wondering whether the `helm upgrade ...` (in the `deploy-jh.sh` file) operation requires helm to be installed on the Kubernetes cluster? As far as I know, this isn't always the case.

No, it does not. It even says so in the README: "Only needed locally. Your kuberenetes cluster does not need to support helm"

> Another thing that we might want to add to the README is how to upgrade to another helm chart. In the current state of things, one needs to run `kubectl delete -f full.yaml` to delete the previous configuration. This wouldn't be possible after applying your changes. Do you know how one should deal with that?

I am very confused about this question. Why would you have to delete the previous configuration? You can simply upgrade to the next version of the chart, that is the purpose of using helm.

**Comment by csadorf** [comment]
@yakutovicha This is ready for final review and merge.

**Review by yakutovicha — APPROVED** [review]
Looks good, thanks @csadorf

**Pull request merged**
